# Generated by Django 4.2.7 on 2023-11-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='birth',
            new_name='fechanacimiento',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.AddField(
            model_name='contact',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
