# Generated by Django 4.2.7 on 2023-11-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_rename_birth_contact_fechanacimiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='telefono',
        ),
    ]
