# Generated by Django 4.1.13 on 2023-11-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_rename_phone_contact_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='fechanacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
    ]
